---
- hosts: dev
  become: true
  tasks:
    - name: Ensure required packages are installed
      ansible.builtin.yum:
        name:
          - python3
          - python3-pip
          - yum-utils
        state: present

    - name: Add Docker repository
      ansible.builtin.command:
        cmd: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker CE
      ansible.builtin.yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start and enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Install Docker SDK for Python
      ansible.builtin.pip:
        name: docker
        state: present

    - name: Pull the latest image
      community.docker.docker_image:
        name: shiakahmed53/appdemo
        tag: latest
        source: pull

    - name: Run the application container
      community.docker.docker_container:
        name: ansibleappc2
        image: shiakahmed53/appdemo:latest
        state: started
        restart_policy: always
        published_ports:
          - "8080:8080"
