---
- hosts: dev
  become: true
  tasks:
    - name: Ensure community.docker collection is installed
      ansible.builtin.command: ansible-galaxy collection install community.docker --force
      changed_when: false

    - name: Ensure required packages are installed
      ansible.builtin.dnf:
        name:
          - python3
          - python3-pip
          - dnf-plugins-core
        state: present

    - name: Add Docker CE repository
      ansible.builtin.command:
        cmd: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker CE
      ansible.builtin.dnf:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start and enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Install Docker SDK for Python
      ansible.builtin.pip:
        name: docker
        state: present

    - name: Run the application container
      community.docker.docker_container:
        name: hariapp
        image: "shiakahmed53/appdemo1:latest"
        state: started
        restart_policy: always
        published_ports:
          - "8080:8080"
